### ISSUE TITLE
Have You Seen HTMX?

### ISSUE THREAD

**Issue by mkeneqa** [kasta-ua/twinspark-js#1]
The Intercooler JS successor is [HTMX](https://htmx.org/), with no Jquery dependency. Could you help explain how this library differs and why one would choose TwinsparkJS from HTMX?

**Comment by timuruski** [comment]
The author has a blog post explaining the impetus for this project, which started before HTMX was released.
https://solovyov.net/blog/2020/a-tale-of-webpage-speed-or-throwing-away-react/

**Comment by metapone** [comment]
Alex don't like inheritance in his code. He wrote about it in his blog.

> Inheritance is particularly painful here. In Intercooler, if you declared ic-target on the body, all tags inside will think it’s their target too. So you include a component somewhere in HTML tree and an attribute higher on tree changes this component behavior. I mean this is a freaking dynamic scope, I want none of that! :)
> Funnily enough, after about a month of dabbling with TwinSpark, Intercooler’s author announced that he’s doing a jQuery-less modern version: htmx. :) It has really good extensions points, so maybe it’s possible to add batching… but inheritance is still there. :-(
