### ISSUE TITLE
twinspark та npm-registry

### ISSUE THREAD

**Issue by vldmr-k** [kasta-ua/twinspark-js#14]
Доброго дня!
А можливо додати лібу в npm-registry щоб встановлювати її через npm, yarn?

**Comment by piranha** [comment]
А який юзкейс? Ну типу з моєї колокольні здається, що простіше вгетом менеджити, ніж цілий нпм заводити заради 1 файлика.

**Comment by vldmr-k** [comment]
зазделегіть в проекта не тілки один файлік) 
там ще всякі пережимачи js,css. оптимизатори зоображень, перепакування svg в спрайти і т д) 

+ простіший апдейт twinspark в майбутьньому, чи щось таке
