### ISSUE TITLE
як замінити store pattern?

### ISSUE THREAD

**Issue by vldmr-k** [kasta-ua/twinspark-js#17]
Вводні данні.

Уявимо що на сторінці є 4 місця, які треба оновлювати після якихось дій. Хай це буде компонент counter який перемножае ціну товара на кілкість в input counter.

Як це правильно організувати в twinspark?

Думки
1) запіляхати функця htmlToHtml і передати як рагументи всі місця які треба оновити, але це не дуже удобно. Бо якщо добавиться на сторінку ще один компонент counter - то це буде просто витік мозку.
2) реалізувати це через сервер та ts-swap-push (фігня повна, але як хак може і норм)

В тому самому react/vue/svelte, це вирішуеться store - як це вирішити в ts без больових відчуттів?

PS: Якщо що, то це реальний кейс. Є магаз, в ньому на сторінці товара є два компонента каунтера (статичний і флоатовий). при клікі на + значення збільшуеться, також оновлюється ціна на кнопкі "Поклад в корзину".

**Comment by piranha** [comment]
Ну тут value proposition в тому, що ти не робиш ніяких сховищ і нічого такого. Ти робиш це через сервер. 

Користувач натискає "додати в корзину"? Відправляється запит на сервер і сервер у відповідь присилає хтмл-код, яким треба оновити сторінку. Якщо не всю, то `ts-swap-push` — це саме для того і вигадано було. Типу оновлюється якесь "основне" місце і з ним разом приїздять додаткові.

Чи можна в пам'яті жсом це зробити? Можна, можна написати наприклад екшен. Але імхо у кейсах, коли все одно треба ганяти щось через сервер (додавання в корзину) — то не треба того.
