### ISSUE TITLE
twinspark.js.org domain

### ISSUE THREAD

**Issue by roman-koshchei** [kasta-ua/twinspark-js#23]
[js.org](https://js.org) provide a free domain for javascript-related projects. You can quickly get `twinspark.js.org` domain. It will be excellent for popularizing the library. Htmx is getting attention last few weeks. TwinSpark is also a valuable library with a similar purpose that can also be an interesting alternative to htmx. I also appreciate moving development forward from the people of my native country.

**Comment by piranha** [comment]
Had no idea about this service! Seems like a good idea. :-)

**Comment by roman-koshchei** [comment]
https://github.com/js-org/js.org/pull/8188#pullrequestreview-1389889400

js.org can't approve pull request. Because CNAME file should be in the root of GitHub pages. I am not sure where is in this repo root for GitHub pages stuff (maybe it should be www). So I can't do it myself.
