### ISSUE TITLE
Вопросы к стриму "Викинь ти той React"

### ISSUE THREAD

**Issue by JAremko** [kasta-ua/twinspark-js#3]
@piranha На прошлом стриме был вопросник.  Почему бы не бахнуть и к [этому](https://www.youtube.com/watch?v=uNF7QmFiQaw)?

Чаво больше всего интересно:
 - Почему не получилось пофиксить реакт сервер сайд рендерингом, отложенной загрузкой и прочими оптимизациями? Было бы сложнее/дороже, невозможно или пришло осознание того что э-комерсу реакт оверкилл?
 - Реакт вообще ненужен? Может тогда и для SPA юзать какой нибудь Vaadin?
 - Не будет ли дешевле перейти на htmx, что бы не майнтейнить свою либу. Чем она лучше? Может все таки форкнуть/закомитить нужные улучшения в htmx и юзать его?
 - Планируете так и рендерить html фрагменты на сервере rum-ом?
 - Не было бы лучше разделить куски страницы на шаблоны (`<template>` или тупо регекспом подставлять) и тянуть с сервера только данные.  Теми же service worker можно прозрачно проксировать запросы  с минимальными измененьями в самой либе. Тогда можно будет кешировать шаблоны, префетчить шаблоны альтернативных вьюшек когда запрашивается  родительский элемент, отображать шаблон с плейсхолдер данными пока реальные подтягиваются и тп. Серверный код тоже не будет сильно сложнее. Если объяснить генератору html фрагментов концепцию шаблона (верстка+данные) то он сможет сразу генерить для эндпоинта где это запрашивается одним куском + еще 2 с данными и шаблоном отдельно. 
-  Как обстоит дело с дебагом и насколько агрессивно все кешируется? Если от юзера прилетел кривой запрос, то как понять как он оказался в стейте который позволяет его сделать?
- [`queue.request = setTimeout(executeRequests, 16);`](https://github.com/kasta-ua/twinspark-js/blob/2d627ea5faff7ecfe6798861d7bbc3431285030a/twinspark.js#L810) трюк с `16` реально с  фреймрейтом помогает? 
- Этот [`IntersectionObserver`](https://github.com/kasta-ua/twinspark-js/blob/2d627ea5faff7ecfe6798861d7bbc3431285030a/twinspark.js#L1012) интересная штука. Может устроить тур по коду?

**Comment by JAremko** [comment]
@piranha  Спасибо! Ждем стрима.

**Comment by piranha** [comment]
А я правильно понял, что Vaadin на беке кучу жса генерит по инструкциям на джаве? Или в чём там суть?

**Comment by JAremko** [comment]
@piranha Да, основная идея это пилить убийцы экселей и тп руками корпоративных жавистов - в браузере.
Клиентская часть это чисто вьюшка(раньше на GWT щя веб компоненты) и да это дело из готовых блоков на Java собирается. Логика на сервере гоняется поэтому оно на каждый чих раундтрипит. Кто-то пытался Clojure прихреначить но хзн.  Вопрос только один. Зачем это в браузере если оно с пингом работать не будет :confused:  

Демка https://demo.vaadin.com/dashboard

**Comment by JAremko** [comment]
@piranha  

> На самом деле с радостью, но у него есть 1 вещь, которую Карсон похоже любит, что ли: наследование. Меня она тупо бесит. Я покажу потом пример, о чём речь, но он чёта вообще не горит желанием это менять, а я не могу себя заставить юзать. Я бы сказал, что это можно вообще пообсуждать, в чём разница с htmx (и почему unpoly кошмар :)).
Работает клёво, лучше чем стандартные "контроллер + шаблон", так что пока так и продолжаем

А нельзя законтрибутить в htmx конфиг который эту фишку вырубает? Или она прямо там весь код пронизывает? Тут кажется что-то в этом духе обсуждали и даже замаржили https://github.com/bigskysoftware/htmx/issues/244

**Comment by piranha** [comment]
Ну мож, надо подумать. Мне просто кажется что конфигурация такого левела - это плохо. Эта херня учит плохому, вот шо. Но нельзя не отметить то, что хтмх хорошо пошел и чувак прилично сил вложил и продолжает. 

Кароч, надо подумать. Вкороткую - сапортить твинспарк много времени не занимает, зато он работает ровно как задумано. :) 

Ну я думал думал, и батчи тоже придется контрибьютить, а это наносит довольно серьезные ограничения в виде того как хтмл с сервера надо возвращать. В твинспарке оно так задумано, а там обратную совместимость поломает, или придется выдумывать два режима получения...

А без батчей эта вся херня становится неэффективной до крику)

**Comment by JAremko** [comment]
@piranha  Про батчи тоже тикеты были https://github.com/bigskysoftware/htmx/issues/430 и https://github.com/bigskysoftware/htmx/issues/129 (магия какая-то).

Батчи как адхок с таймером должно быть несложно запихнуть. Может как реальное расширение уже попотеть 
 прийдется.. Но интерес к этому похожее есть. Кстати у них [интересные расширения](https://htmx.org/extensions/#reference) есть.

**Comment by JAremko** [comment]
>  Ну я думал думал, и батчи тоже придется контрибьютить, а это наносит довольно серьезные ограничения в виде того как хтмл с сервера надо возвращать. В твинспарке оно так задумано, а там обратную совместимость поломает, или придется выдумывать два режима получения...

Немного поколупал. Там для парсинга ответа есть экстеншен поинт [`transformResponse`](https://github.com/bigskysoftware/htmx/blob/49b517e1c11802919e5c1078aa0843bdb1b3482c/src/htmx.js#L2369) его юзает [`темплейтер`](https://github.com/bigskysoftware/htmx/blob/49b517e1c11802919e5c1078aa0843bdb1b3482c/src/ext/client-side-templates.js#L2) может прямо из этой чтуки и посвапать дополнительные элементы на худой конец :thinking:

**Comment by JAremko** [comment]
@piranha  Если я правильно понял то логика наследование запихана в [` getClosestMatch`](https://github.com/bigskysoftware/htmx/blob/49b517e1c11802919e5c1078aa0843bdb1b3482c/dist/htmx.js#L107) который просто рекурсивно чекает родительский элемент. Так что тут вообще просто будет это дело вырубить конфигом/патчем.

**Comment by piranha** [comment]
Figma - це точно коли не треба :)

**Comment by s-stude** [comment]
- як ви хендлите інший юай для авторизованих користувачів? 
- чи я правильно розумію, що кожний блок (який для авторизованих виглядяє по іншому) має зробити xhr, щоб отримати новий ui?
- де складати усі html шматочки темплейтів, якщо я маю оперувати не компонентом (типу меню юзера) а меню айтемом у випадку оновлення twinspark-ом якогось там шматка html? [доречі це дуже схоже на той самий підхід з jquery де ми оновлюемо цсс чи чайлд ноду. чи не стане це кошмаром?]
